### ISSUE TITLE
can not open "Swap.h"

### ISSUE THREAD

**Issue by Lei2050** [galeone/ue-plugin-tutorial#1]
I followed the steps depicted in blog: https://pgaleone.eu/2022/05/27/unreal-engine-third-party-linux-abi-compatibility/
but a error occurs: can not open "Swap.h".
I checked the config files of "*.cs"，nothing wrong were found.
Pls Help !

**Comment by galeone** [comment]
Hi, first of all thanks for reading the article! :partying_face: 

Have you created the very same structure of this repository locally? The swap file must be in the `Public` directory, as you can see here https://github.com/galeone/ue-plugin-tutorial/blob/main/Plugins/Swap/Source/Swap/Public/Swap.h

**Comment by Lei2050** [comment]
> 

I changed my IDE from Visual Studio to Rider, the error became a LINK ERROR. Comparing your code, my "Swap.h" file is missing "SWAP_API". The auto generated Swap.h is like this "class FSwapModule : public IModuleInterface". After adding "SWAP_API", it runs successfully. I wonder why UE5 automatically omit the "SWAP_API"......

Again, Visual Studio tortured me.

Thank you for you blog, it helps a lot for me.
